name: Lint Laravel Project with Pint

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências do Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-progress --prefer-dist

      - name: Rodar o Pint para linting do código
        run: |
          ./vendor/bin/pint --test
